<a href="https://colab.research.google.com/github/AndreAntonioCampos/FIAP_POS/blob/main/Modulo1_Analise_Exploratorio_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ANALISANDO DADOS DE PRODUÇÃO HOSPITALAR

#IMPORTANDO A BIBLIOTECA PANDAS

In [ ]:
import pandas as pd

#CARREGANDO A TABELA E TRATANDO AS COLUNAS
encoding='ISO-8859-1 = Transformando em UTF-8
skiprows=3  = Desconsidera a 3 primeiras linhas da tabela
sep = ";"   = Informando que o separador é ;
skipfooter=12   = Excluindo as 12 linhas finais que tem informações que não são dados
Thousands = "."   = Trocando a , por ponto em separador de milhar no valor
decimal = ","   = Informando que o separador de casas decimais é ,

In [ ]:
dados = pd.read_csv('/content/A152918189_28_143_208.csv', encoding='ISO-8859-1',
            skiprows=3, sep = ";" , skipfooter=12, thousands=".", decimal=",")
print(dados)

      Unidade da Federação     2008/Jan      2008/Fev      2008/Mar  \
0              11 Rondônia   1388528.39  2.931283e+06  1.541683e+06
1                  12 Acre    902416.00  1.497206e+06  1.794028e+06
2              13 Amazonas   4735529.42  7.118991e+06  8.196635e+06
3               14 Roraima    657889.53  7.779393e+05  7.186880e+05
4                  15 Pará  18864744.11  1.955376e+07  2.193734e+07
5                 16 Amapá   1120973.34  1.268740e+06  9.746512e+05
6             17 Tocantins   3441592.69  4.985689e+06  6.205613e+06
7              21 Maranhão  10723506.39  1.355968e+07  1.398514e+07
8                 22 Piauí   7985142.43  1.007993e+07  1.029837e+07
9                 23 Ceará  15539821.90  2.573510e+07  2.872463e+07
10  24 Rio Grande do Norte   5947814.08  9.509756e+06  1.035224e+07
11              25 Paraíba  10723002.45  1.138627e+07  1.205364e+07
12           26 Pernambuco  14393949.89  2.418140e+07  2.999130e+07
13              27 Alagoas   6243726.32  8.376622e+06  8.408336e+06
14              28 Sergipe   2780750.11  3.676483e+06  5.051474e+06
15                29 Bahia  21211522.47  2.818930e+07  3.418148e+07
16         31 Minas Gerais  45671659.76  7.019404e+07  7.923134e+07
17       32 Espírito Santo   5456723.98  9.102213e+06  1.024960e+07
18       33 Rio de Janeiro  23025258.52  2.839431e+07  4.456706e+07
19            35 São Paulo  91678473.48  1.486775e+08  1.560873e+08
20               41 Paraná  38266347.46  5.538467e+07  5.380132e+07
21       42 Santa Catarina  16504913.45  2.565143e+07  2.674352e+07
22    43 Rio Grande do Sul  30931325.46  5.736342e+07  5.154779e+07
23   50 Mato Grosso do Sul   5377392.11  7.002473e+06  8.423933e+06
24          51 Mato Grosso   4795299.01  8.684882e+06  7.886243e+06
25                52 Goiás  15310637.29  2.225867e+07  2.144252e+07
26     53 Distrito Federal   4745919.19  7.632481e+06  9.647203e+06

        2008/Abr      2008/Mai      2008/Jun      2008/Jul      2008/Ago  \
0   1.525315e+06  1.645954e+06  1.406151e+06  3.065279e+06  3.231495e+06
1   1.730469e+06  1.819444e+06  1.828496e+06  2.511755e+06  2.089107e+06
2   8.259378e+06  7.831400e+06  8.477274e+06  9.368859e+06  9.352533e+06
3   8.399944e+05  8.623480e+05  8.324407e+05  9.966931e+05  8.942712e+05
4   2.084283e+07  2.324995e+07  2.324069e+07  2.400222e+07  2.334122e+07
5   1.141137e+06  8.663462e+05  1.440979e+06  1.426659e+06  1.475551e+06
6   4.984482e+06  5.511002e+06  4.927934e+06  5.445602e+06  5.413710e+06
7   1.480942e+07  1.450573e+07  1.490809e+07  1.578490e+07  1.519531e+07
8   1.077598e+07  1.039836e+07  1.052825e+07  1.104011e+07  1.054918e+07
9   3.067646e+07  3.060445e+07  3.127240e+07  3.092539e+07  2.785144e+07
10  1.085511e+07  1.116017e+07  1.047507e+07  1.138635e+07  1.064082e+07
11  1.265353e+07  1.221511e+07  1.225693e+07  1.275541e+07  1.287258e+07
12  3.480620e+07  3.214799e+07  3.223909e+07  3.268564e+07  3.545704e+07
13  9.090795e+06  9.338771e+06  1.006821e+07  9.887062e+06  9.373432e+06
14  5.046063e+06  4.741152e+06  5.401260e+06  5.521904e+06  5.238398e+06
15  3.902693e+07  4.294957e+07  4.702597e+07  4.748170e+07  4.693125e+07
16  7.713654e+07  8.055444e+07  9.475852e+07  8.536006e+07  8.472253e+07
17  1.125383e+07  1.019862e+07  1.336426e+07  1.303537e+07  1.258860e+07
18  4.405460e+07  4.491102e+07  4.805621e+07  4.987238e+07  5.091271e+07
19  1.612271e+08  1.871194e+08  1.872911e+08  1.943984e+08  1.848545e+08
20  5.246031e+07  5.441962e+07  5.781169e+07  5.809424e+07  5.698277e+07
21  2.718149e+07  2.684531e+07  2.990976e+07  3.078914e+07  3.125085e+07
22  5.667334e+07  4.839773e+07  5.241343e+07  5.663638e+07  5.611305e+07
23  8.797488e+06  9.770422e+06  1.090539e+07  1.024930e+07  9.671553e+06
24  8.794110e+06  9.231645e+06  1.022176e+07  9.163314e+06  9.243149e+06
25  2.092121e+07  2.161597e+07  1.827004e+07  2.054052e+07  2.065073e+07
26  1.109873e+07  1.289172e+07  1.285013e+07  1.256565e+07  1.371086e+07

        2008/Set  ...      2021/Jan      2021/Fev      2021/Mar      2021/Abr  \
0   3.117179e+06  ...  9.858841e+06  9.806315e+06  1.494637e+07  1.555293e+07
1   2.275709e+06  ...  3.715723e+06  3.538428e+06  4.077046e+06  6.307617e+06
2   9.363099e+06  ...  2.162170e+07  2.616368e+07  2.344583e+07  2.315404e+07
3   9.104242e+05  ...  3.266928e+06  3.519774e+06  4.437161e+06  5.171371e+06
4   2.517226e+07  ...  3.881379e+07  3.925157e+07  4.063970e+07  4.660826e+07
5   1.651341e+06  ...  2.807808e+06  2.822559e+06  3.188211e+06  3.616822e+06
6   5.596670e+06  ...  7.297673e+06  9.875312e+06  1.065104e+07  9.365633e+06
7   1.495128e+07  ...  3.179885e+07  3.261145e+07  4.453434e+07  5.000074e+07
8   1.089920e+07  ...  2.268939e+07  2.098326e+07  2.160927e+07  2.740579e+07
9   3.036272e+07  ...  5.232125e+07  5.623521e+07  6.836016e+07  7.854534e+07
10  1.133603e+07  ...  2.807442e+07  2.658153e+07  2.844410e+07  3.593031e+07
11  1.255830e+07  ...  1.955267e+07  2.154116e+07  2.640437e+07  2.957740e+07
12  3.366826e+07  ...  8.391385e+07  7.819653e+07  8.793369e+07  1.039581e+08
13  9.563580e+06  ...  1.754857e+07  1.858748e+07  2.232305e+07  2.682628e+07
14  5.187912e+06  ...  1.206086e+07  1.322610e+07  1.350702e+07  1.492872e+07
15  4.488338e+07  ...  8.004195e+07  8.238539e+07  1.020127e+08  1.155447e+08
16  8.460176e+07  ...  1.841231e+08  1.873205e+08  2.114789e+08  2.392220e+08
17  1.272743e+07  ...  4.095465e+07  4.237464e+07  4.819583e+07  5.503735e+07
18  4.927035e+07  ...  9.436035e+07  9.297707e+07  1.133550e+08  1.193017e+08
19  1.886364e+08  ...  3.560972e+08  3.503669e+08  4.068667e+08  4.742798e+08
20  5.754908e+07  ...  1.235285e+08  1.336361e+08  1.413855e+08  1.565325e+08
21  3.001968e+07  ...  7.292978e+07  7.592330e+07  8.538712e+07  8.800435e+07
22  5.535622e+07  ...  1.200301e+08  1.119450e+08  1.343390e+08  1.445265e+08
23  1.021851e+07  ...  2.201409e+07  2.524996e+07  2.602883e+07  2.684042e+07
24  9.052355e+06  ...  1.948153e+07  1.906485e+07  2.428373e+07  3.107621e+07
25  2.086844e+07  ...  4.647390e+07  4.432946e+07  5.770139e+07  6.162324e+07
26  1.316511e+07  ...  2.352705e+07  2.276695e+07  3.183192e+07  3.841012e+07

        2021/Mai      2021/Jun      2021/Jul      2021/Ago      2021/Set  \
0   1.626901e+07  1.538053e+07  1.422881e+07  1.242787e+07   10345616.78
1   6.354514e+06  3.461663e+06  4.979239e+06  4.138752e+06             -
2   2.612770e+07  2.644706e+07  2.445779e+07  2.273136e+07   19840265.30
3   4.266255e+06  3.103980e+06  3.743331e+06  3.781921e+06    3150835.05
4   5.531088e+07  4.821505e+07  4.580175e+07  4.326288e+07   14569318.55
5   4.379596e+06  3.808085e+06  5.211716e+06  5.263138e+06    5032883.11
6   9.493726e+06  1.065036e+07  9.790961e+06  9.735208e+06     773480.42
7   5.298495e+07  5.046155e+07  5.050001e+07  4.150170e+07   36250671.51
8   3.011076e+07  3.107517e+07  2.940174e+07  2.769490e+07   20752326.97
9   8.692838e+07  1.099095e+08  9.038765e+07  7.573188e+07   75197971.95
10  3.676421e+07  3.670801e+07  3.598910e+07  3.236937e+07   24063936.32
11  3.473563e+07  3.423169e+07  2.982749e+07  2.808245e+07   24377900.38
12  1.231094e+08  1.254077e+08  1.149716e+08  1.028010e+08   83993757.90
13  2.965147e+07  2.815568e+07  2.899250e+07  2.472316e+07   19758417.78
14  1.772466e+07  1.963347e+07  1.889410e+07  1.429774e+07   12133818.13
15  1.154056e+08  1.291897e+08  1.328828e+08  1.100636e+08   99862227.64
16  2.511486e+08  2.652824e+08  2.585785e+08  2.419318e+08  193773519.61
17  5.401959e+07  5.141656e+07  5.443142e+07  4.462795e+07   38395547.28
18  1.339250e+08  1.331476e+08  1.322160e+08  1.330509e+08  128586740.23
19  5.101184e+08  5.227484e+08  5.154613e+08  4.603486e+08  393119442.09
20  1.662034e+08  1.796777e+08  1.829497e+08  1.780401e+08  121946453.33
21  8.439795e+07  9.460985e+07  9.754521e+07  1.025289e+08   83493556.56
22  1.473467e+08  1.483085e+08  1.498138e+08  1.345690e+08  120016574.60
23  2.864920e+07  3.392048e+07  3.155202e+07  3.631052e+07   32338424.49
24  3.188584e+07  3.318768e+07  3.894321e+07  3.776361e+07   27274369.25
25  5.873777e+07  6.478946e+07  7.202116e+07  7.090287e+07   64176809.02
26  3.153282e+07  3.062936e+07  2.966272e+07  2.728877e+07   28509985.96

           Total
0   1.088060e+09
1   4.752903e+08
2   2.061943e+09
3   3.525463e+08
4   4.968812e+09
5   3.371820e+08
6   1.110345e+09
7   4.161326e+09
8   2.450509e+09
9   7.118540e+09
10  2.867428e+09
11  2.796673e+09
12  9.243658e+09
13  2.394793e+09
14  1.313873e+09
15  1.049850e+10
16  2.189955e+10
17  3.710942e+09
18  1.113187e+10
19  4.429099e+10
20  1.567216e+10
21  8.392939e+09
22  1.361334e+10
23  2.516383e+09
24  2.386584e+09
25  5.380181e+09
26  2.778457e+09

[27 rows x 167 columns]

<ipython-input-18-17a4995625f0>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  dados = pd.read_csv('/content/A152918189_28_143_208.csv', encoding='ISO-8859-1',

#Trazendo as 5 principais da tabela

In [ ]:
dados.head()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
0,11 Rondônia,1388528.39,2931283.42,1541682.52,1525314.96,1645953.84,1406150.68,3065279.01,3231494.61,3117178.63,...,9858841.18,9806315.07,14946369.28,15552930.66,16269008.71,15380532.08,14228814.25,12427865.05,10345616.78,1.088060e+09
1,12 Acre,902416.00,1497206.26,1794028.48,1730469.42,1819443.92,1828496.00,2511754.59,2089107.14,2275708.53,...,3715723.12,3538427.92,4077045.92,6307616.67,6354514.15,3461663.11,4979239.30,4138751.64,-,4.752903e+08
2,13 Amazonas,4735529.42,7118990.57,8196635.49,8259378.42,7831399.90,8477273.62,9368858.72,9352532.70,9363099.35,...,21621697.26,26163677.75,23445832.76,23154039.32,26127701.15,26447055.27,24457791.81,22731356.54,19840265.30,2.061943e+09
3,14 Roraima,657889.53,777939.31,718688.03,839994.39,862347.96,832440.66,996693.09,894271.18,910424.17,...,3266928.47,3519773.73,4437161.10,5171370.92,4266254.94,3103979.88,3743330.65,3781921.16,3150835.05,3.525463e+08
4,15 Pará,18864744.11,19553758.20,21937342.70,20842829.69,23249952.88,23240687.56,24002223.56,23341218.03,25172261.32,...,38813794.18,39251569.26,40639703.77,46608262.09,55310881.51,48215050.10,45801750.84,43262884.30,14569318.55,4.968812e+09

#Trazendo a 5 ultimas da tabela

In [ ]:
dados.tail()

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
22,43 Rio Grande do Sul,30931325.46,57363420.01,51547794.07,56673338.49,48397733.07,52413429.62,56636376.98,56113054.70,55356224.30,...,1.200301e+08,1.119450e+08,1.343390e+08,1.445265e+08,1.473467e+08,1.483085e+08,1.498138e+08,1.345690e+08,120016574.60,1.361334e+10
23,50 Mato Grosso do Sul,5377392.11,7002472.61,8423933.19,8797487.68,9770421.80,10905392.18,10249299.82,9671553.45,10218511.05,...,2.201409e+07,2.524996e+07,2.602883e+07,2.684042e+07,2.864920e+07,3.392048e+07,3.155202e+07,3.631052e+07,32338424.49,2.516383e+09
24,51 Mato Grosso,4795299.01,8684882.23,7886243.14,8794109.79,9231645.40,10221763.77,9163314.28,9243148.81,9052354.89,...,1.948153e+07,1.906485e+07,2.428373e+07,3.107621e+07,3.188584e+07,3.318768e+07,3.894321e+07,3.776361e+07,27274369.25,2.386584e+09
25,52 Goiás,15310637.29,22258668.68,21442515.75,20921212.45,21615970.67,18270043.87,20540517.13,20650730.67,20868443.56,...,4.647390e+07,4.432946e+07,5.770139e+07,6.162324e+07,5.873777e+07,6.478946e+07,7.202116e+07,7.090287e+07,64176809.02,5.380181e+09
26,53 Distrito Federal,4745919.19,7632480.67,9647203.26,11098732.99,12891719.72,12850125.67,12565646.74,13710857.89,13165106.20,...,2.352705e+07,2.276695e+07,3.183192e+07,3.841012e+07,3.153282e+07,3.062936e+07,2.966272e+07,2.728877e+07,28509985.96,2.778457e+09

#Trazendo a média de valores

In [ ]:
print(dados.mean())

TypeError: Could not convert ['11 Rondônia12 Acre13 Amazonas14 Roraima15 Pará16 Amapá17 Tocantins21 Maranhão22 Piauí23 Ceará24 Rio Grande do Norte25 Paraíba26 Pernambuco27 Alagoas28 Sergipe29 Bahia31 Minas Gerais32 Espírito Santo33 Rio de Janeiro35 São Paulo41 Paraná42 Santa Catarina43 Rio Grande do Sul50 Mato Grosso do Sul51 Mato Grosso52 Goiás53 Distrito Federal'
 '3605007.43-9730634.161701611.2527967969.222034329.786542918.1419722895.5112247027.2934471579.0613213817.6016117680.2437971068.1711170853.096341601.0653839068.5996911075.3815382323.4652027721.77220292973.6665843824.7337380382.9366425009.3611997775.9210810420.6525227845.7414487053.32'
 '10345616.78-19840265.303150835.0514569318.555032883.11773480.4236250671.5120752326.9775197971.9524063936.3224377900.3883993757.9019758417.7812133818.1399862227.64193773519.6138395547.28128586740.23393119442.09121946453.3383493556.56120016574.6032338424.4927274369.2564176809.0228509985.96'] to numeric

#Formatando os valor de 1.512685e+07 para 15126846.64

In [ ]:
pd.options.display.float_format = "{:.2f}".format

#Trazendo a média dos valores formatado

In [ ]:
dados.mean()

#Captura uma unica coluna

In [ ]:
dados["2008/Ago"]

#Média da Serie capturada

In [ ]:
dados["2008/Ago"].mean()

#PLOTAR os dados, ou seja quero criar uma analise de um determinado dado

In [ ]:
dados.plot(x = "Unidade da Federação", y = "2008/Ago")

In [ ]:
#

#Trabalhando o Grafico

In [ ]:
#Neste caso, não fico umuito bom o visual do grafico pois não mostra todas as informações que eu quero
#Vamos usar um grafico de barras e para isso, usamos o comando "kind = bar"

In [ ]:
dados.plot(x = "Unidade da Federação", y = "2008/Ago", kind = "bar")

#Formatando o tamanho horizontal e vertical

In [ ]:
#Usando o comando "Figzise(H,V)"

In [ ]:
dados.plot(x = "Unidade da Federação", y = "2008/Ago", kind = "bar", figsize=(10,7))

#Formatação do valor do Grafico

In [ ]:
#Vamos fortatar o Eixo(axis) e neste caso vamos formatar o eixo Y()
# darei o nome de axis(variavel) para o código da criação do grafico

In [ ]:
axis = dados.plot(x = "Unidade da Federação", y = "2008/Ago", kind = "bar", figsize=(10,7))